CREATE DATABASE IF NOT EXISTS annonceo;
USE annonceo;

CREATE TABLE annonce(
id_annonce INT(3) NOT NULL AUTO_INCREMENT,
titre VARCHAR(255) NOT NULL,
description_courte VARCHAR(255) NOT NULL,
descritpion_longue TEXT NOT NULL,
prix REAL NOT NULL,
photo VARCHAR(200) NOT NULL,
pays VARCHAR(20) NOT NULL,
ville VARCHAR(20) NOT NULL,
adresse VARCHAR(50) NOT NULL,
cp INT(5),
id_membre INT(3) NOT NULL,
id_photo INT(3) NOT NULL,
id_categorie INT(3) NOT NULL,
date_enregistrement DATETIME NOT NULL,
PRIMARY KEY(id_annonce)
)ENGINE=InnoDB;

CREATE TABLE photo(
id_photo INT(3) NOT NULL AUTO_INCREMENT,
photo1 VARCHAR(255) DEFAULT NULL,
photo2 VARCHAR(255) DEFAULT NULL,
photo3 VARCHAR(255) DEFAULT NULL,
photo4 VARCHAR(255) DEFAULT NULL,
photo5 VARCHAR(255) DEFAULT NULL,
PRIMARY KEY(id_photo)
)ENGINE=InnoDB;

CREATE TABLE commentaire(
id_commentaire INT(3) NOT NULL AUTO_INCREMENT,
id_membre INT(3) NOT NULL,
id_annonce INT(3) NOT NULL,
commentaire TEXT NOT NULL,
date_enregistrement DATETIME NOT NULL,
PRIMARY KEY(id_commentaire)
)ENGINE=InnoDB;

CREATE TABLE note(
id_note INT(3) NOT NULL AUTO_INCREMENT,
id_membre1 INT(3) NOT NULL,
id_membre2 INT(3) NOT NULL,
note INT(3) NOT NULL,
avis TEXT NOT NULL,
date_enregistrement DATETIME NOT NULL,
PRIMARY KEY(id_note)
)ENGINE=InnoDB;

CREATE TABLE categorie(
id_categorie INT(3) AUTO_INCREMENT NOT NULL,
titre VARCHAR(255) NOT NULL,
motscles TEXT DEFAULT NULL,
PRIMARY KEY(id_categorie)
)ENGINE=InnoDB;

CREATE TABLE membre(
id_membre INT(3) AUTO_INCREMENT NOT NULL,
pseudo VARCHAR(20) NOT NULL,
mdp VARCHAR(60) NOT NULL,
nom VARCHAR(20) NOT NULL,
prenom VARCHAR(20) NOT NULL,
telephone VARCHAR(20) NOT NULL,
email VARCHAR(50) NOT NULL,
civilite ENUM('m','f') NOT NULL,
statut INT(1) NOT NULL,
date_enregistrement DATETIME NOT NULL,
PRIMARY KEY(id_membre)
)ENGINE=InnoDB;

